### ISSUE TITLE
Question autograd eigsh

### ISSUE THREAD

**Issue by Jan-David-Black** [fancompute/legume#53]
Hey @momchil-flex, 
I have been trying to figure out a way to differentiate over eigenproblem solvers, that use sparse matrices and only return a set of k eigenvalues. I found your implementation here, that uses Steven Johnsons method. 
I have two questions:
This is equation 7 from Steven Johnsons writeup: 
![Screenshot_20230625-194929_Drive](https://github.com/fancompute/legume/assets/92856893/079f9769-8046-4495-a681-fcad927f345f)

If I understand it correctly the latter part is the vjp:
$$v^T x_p = - \lambda_0^T A_p x + g_\alpha x^T A_p x$$
How does $A_p$ get incorporated in your implementation? 

https://github.com/fancompute/legume/blob/cfa800e8ffabde8f5d621a7d38a77c59a1132780/legume/primitives.py#L199

It seems as if $A_p$ is left out and $x^Tx$ is replaced with $xx^T$. I most probably don't fully understand the underlying AD mechanics.

You also stated in a JAX issue (https://github.com/google/jax/issues/3112) that you modified the formulation to account for Hermitian matrices. What modification did you make?

Sorry to bother you... 
Regards JD

**Comment by momchil-flex** [comment]
> Hey @momchil-flex, I have been trying to figure out a way to differentiate over eigenproblem solvers, that use sparse matrices and only return a set of k eigenvalues. I found your implementation here, that uses Steven Johnsons method. I have two questions: This is equation 7 from Steven Johnsons writeup: ![Screenshot_20230625-194929_Drive](https://user-images.githubusercontent.com/92856893/248601348-079f9769-8046-4495-a681-fcad927f345f.jpg)
> 
> If I understand it correctly the latter part is the vjp: vTxp=−λ0TApx+gαxTApx How does Ap get incorporated in your implementation?
> 
> https://github.com/fancompute/legume/blob/cfa800e8ffabde8f5d621a7d38a77c59a1132780/legume/primitives.py#L199
> 
> It seems as if Ap is left out and xTx is replaced with xxT. I most probably don't fully understand the underlying AD mechanics.

In that note's notation, remember that `Ap` is the derivative of `A` with respect to all the input parameters `p`. However, here our input parameters are just the matrix elements themselves. That is to say, we are writing the vjp for a function `eigsh(A) -> (e, v)` where `e` are the eigenvalues and `v` are the eigenvectors. So `Ap` is a rank-4 tensor which `Ap_{ijkl}` is just something like `delta_ik delta_jl`. This is also what transforms the $x^Tx$ into $xx^T$.

> You also stated in a JAX issue (https://github.com/google/jax/issues/3112) that you modified the formulation to account for Hermitian matrices. What modification did you make?

I believe the only thing that had to change was the use of $v^\dagger$ instead of $v^T$, i.e. the places where `vc` appears in the code instead of what would be a `v` for real symmetric matrices.

Let me know if you have other questions. Vjps are fun! :D Is this for meow? There you probably need more general matrices than Hermitian right? My former colleague at Stanford and current colleague at Flexcompute @weiliangjinca put an `eig` vjp in his autograd RCWA package [here](https://github.com/weiliangjinca/grcwa/blob/5d85c824e3f2243624c23641800f551ee935fac0/grcwa/primitives.py#L36-L56). Probably with some thinking it can be further extended to a subspace of the eigenvalues.
