### ISSUE TITLE
understanding which band to optimize in the tutorial

### ISSUE THREAD

**Issue by zhengqigao** [fancompute/legume#68]
Hi,

Thanks for the nice implementation. I am reading [the tutorial](https://legume.readthedocs.io/en/latest/examples/05_Plane_wave_expansion_with_autograd.html#Optimize-the-waveguide) about optimizing phc. I wonder how we determine ``b_target = Nx*Ny - 3``? From the figure, it seems this ``b_target`` can give us the band at the middle, but why is that? And can we write ``b_target= Nx *Ny -2``? Namely, what is the logic behind setting this value?

Thanks so much for your time!

**Comment by momchil-flex** [comment]
Hmm. Honestly I am not sure if there's a general argument that can be made about which band index should be chosen. I think this was just set by trial and error, i.e. looking at the bands to see which one is the index we want. You can certainly set `b_target = Nx * Ny - 2` if you want to optimize the next higher band.

**Comment by ympc08** [comment]
I have a follow up question:

is it possible that the target index change during the optimization? for example, initially ```b_target = Nx*Ny - 3``` is the band that we want to optimize and after 10 iterations, the index of the band that should be optimized become ```b_target = Nx*Ny - 2```?

Thank you very much for your attention!

**Comment by momchil-flex** [comment]
Yes, it is possible, in fact it is even worse than that. At every k, the frequencies are just ordered by magnitude. We do not try to track bands e.g. by trying to match the eigenvectors (the fields) because it can be quite finicky when there are band crossings. So in the case of a band crossing, e.g. the `b_target = Nx * Ny - 3` band will physically contain states from one band up to the crossing point, and from a different band beyond it. Thus in complicated scenarios where band crossings or switching can happen, it will be important to have some post-processing of the results in your objective function that tries to track the states, or the band, that you are looking for. This could for example be an overlap integral with some starting state. And it should be written with autograd numpy so that it's differentiable.
